# Time series Stationarity

## What is Stationarity?

A time series is stationary if it does not exhibit any long term trends or obvious seasonality.

It has:

- A constant variance through time
- A constant mean through time
- The statistical properties of the time series do not change

### import libraries

In [52]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [53]:
# read in the data
url = '../data/daily-minimum-temperatures.csv'
df = pd.read_csv(url)
df.head()

       Date Daily minimum temperatures
0  1/1/1981                       20.7
1  1/2/1981                       17.9
2  1/3/1981                       18.8
3  1/4/1981                       14.6
4  1/5/1981                       15.8

### Preprocessing

In [54]:
df['Date'] = pd.to_datetime(df['Date']) # Chuyen tu string sang datetime
df = df.sort_values('Date') # sap xep dataset theo thoi gian
df['Daily minimum temperatures'].unique()

array(['20.7', '17.9', '18.8', '14.6', '15.8', '17.4', '21.8', '20',
       '16.2', '13.3', '16.7', '21.5', '25', '20.6', '24.8', '17.7',
       '15.5', '18.2', '12.1', '14.4', '16', '16.5', '18.7', '19.4',
       '17.2', '15.1', '15.4', '15.3', '21.9', '19.9', '16.6', '16.8',
       '17.1', '15', '13.7', '13.9', '18.3', '22', '22.1', '21.2', '18.4',
       '16.1', '15.7', '18.5', '16.9', '17.5', '17.8', '18.6', '17',
       '14.3', '11.4', '16.3', '11.8', '12.2', '14.7', '11.3', '10.6',
       '11.7', '14.2', '11.2', '8.1', '8', '8.8', '13.4', '10.9', '11',
       '14.5', '18.1', '10', '14.9', '15.9', '13', '7.6', '11.5', '13.5',
       '12.4', '13.2', '13.8', '9', '9.8', '8.9', '7.4', '9.9', '9.3',
       '8.6', '11.9', '14', '12', '10.5', '10.7', '10.1', '5.3', '6.6',
       '8.5', '5.9', '3.2', '2.1', '3.4', '5.4', '9.6', '12.3', '12.6',
       '12.8', '11.6', '5.7', '7.1', '2.5', '3.5', '4.6', '7.7', '10.4',
       '9.2', '6.1', '2.7', '4.3', '6.3', '3.8', '4.4', '4.8', '5.8',
       '6.2', '7.3', '10.2', '9.5', '6.5', '7', '8.3', '6.8', '7.2', '5',
       '6.9', '5.2', '3', '5.6', '7.9', '10.3', '9.7', '12.5', '3.9', '6',
       '5.5', '7.5', '7.8', '14.1', '12.9', '9.1', '8.4', '13.6', '9.4',
       '14.8', '16.4', '15.6', '11.1', '15.2', '19.1', '22.2', '24', '18',
       '19.7', '25.2', '20.5', '19.3', '13.1', '19.5', '22.7', '19.2',
       '22.8', '26.3', '8.7', '10.8', '3.7', '3.1', '0', '1.6', '2.6',
       '2.3', '4.5', '8.2', '4', '1.3', '0.8', '4.2', '2.4', '2.8', '3.3',
       '?0.2', '?0.8', '0.9', '2.2', '5.1', '12.7', '3.6', '6.7', '4.7',
       '17.3', '20.3', '22.5', '20.4', '20.1', '21.1', '17.6', '4.9',
       '1.5', '4.1', '0.7', '6.4', '18.9', '?0.1', '19', '24.3', '21',
       '22.4', '21.7', '21.4', '0.6', '0.3', '1.4', '1.7', '2.9', '20.2',
       '23', '24.1', '20.9', '23.4', '23.9', '19.8', '19.6', '0.5', '1.8',
       '21.6'], dtype=object)

cot <b>Daily minimum temperatures</b> co 1 so dong sai format co dau cham ? o truoc, nen can format lai

In [55]:
def temperatures_format(text):
    if(text[0] == '?'): return text[1:]
    return text

df['Daily minimum temperatures'] = df['Daily minimum temperatures'].apply(temperatures_format).astype(float)    # Doi type tu string sang float

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        3650 non-null   datetime64[ns]
 1   Daily minimum temperatures  3650 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 57.2 KB

#### Hau nhu data tu real world deu la khong Stationarity vay nen ta can lam 1 vai buoc de dataset co tinh Stationarity

### Logarithm Transform
Logarithm Transform la ta lay $ ln(y_t) $ de nen cac du lieu ve, lam sao cho phuong sai cua dataset on dinh
$$ Y_t = log(X_t) $$

In [57]:
def log_transform(value):
    if value > 0: return np.log(value) 
    return value

df['temperatures_log'] = df['Daily minimum temperatures'].apply(log_transform)
df.head()

        Date  Daily minimum temperatures  temperatures_log
0 1981-01-01                        20.7          3.030134
1 1981-01-02                        17.9          2.884801
2 1981-01-03                        18.8          2.933857
3 1981-01-04                        14.6          2.681022
4 1981-01-05                        15.8          2.760010

### Differencing
Differencing la lay vi phan, phuong phap nay giup loai bo <b>Trend</b> bang cach lay gia tri hien tai tru cho gia tri truoc do
$$ Y_t = X_t - X_{t-1} $$
- $ Y_t $: Gia tri hien tai
- $ X_t $: Thoi gian hien tai
- $ X_{t-1} $: Thoi gian truoc do

luu y: Vi cong thuc la lay gia tri hien tai tru cho gia tri truoc do nen dong dau tien cua dataset se bi NaN vay nen ta se hy sinh dong nay bang cach xoa no di.

In [ ]:
df['temperatures_diff'] = df['Daily minimum temperatures'].diff()
df = df.dropna() # Xoa dong dau tien
df.head()

        Date  Daily minimum temperatures  temperatures_log  temperatures_diff
1 1981-01-02                        17.9          2.884801               -2.8
2 1981-01-03                        18.8          2.933857                0.9
3 1981-01-04                        14.6          2.681022               -4.2
4 1981-01-05                        15.8          2.760010                1.2
5 1981-01-06                        15.8          2.760010                0.0

### Stationarity Test
Bay gio ta co the kiem tra tinh Stationarity cua dataset bang: <b>ADF test (Augmented Dickey–Fuller)</b>

ADF la kiem tra 1 thu goi la <b>Unit Root (Nghiem don vi)</b>, neu:
- Co Unit Root, no khong Stationarity
- Khong co Unit Root, no khong Stationarity